# Generated by Django 5.2.8 on 2026-01-25 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anonymous')),
                ('texto', models.TextField()),
                ('fecha_publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_global', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, default='imagenes/default/def.png', null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('passwd', models.CharField(max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('ban_razon', models.TextField(default='Sin novedad', null=True)),
                ('ban_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anonymous')),
                ('texto', models.TextField()),
                ('fecha_publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_global', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_post_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.posts')),
            ],
        ),
    ]
