# Generated by Django 5.2.8 on 2025-12-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('hora_creada', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('ban_razon', models.TextField(default='Sin novedad', null=True)),
                ('ban_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('hora_creada', models.TimeField(auto_now=True)),
                ('id_post_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.posts')),
            ],
        ),
    ]
